name: Lake House Communications
favicon: null
layout_spectrum: 0.16004041046835482
typography_spectrum: 0.3650840150658041
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.18411444150842726
  lightness: 0.39040632522664964
  saturation: 0.7596091479063034
  rhythmicContrast: 0.23905356810428202
purpose: []
